server:
  port: 8080
  servlet:
    context-path: /report
spring:
  profiles:
    active: dev
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://106.52.120.217/hz?characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
#    username: root
#    password: GUO;chuang.123
#    jackson:
#        time-zone: GMT+8
#        date-format: yyyy-MM-dd HH:mm:ss
    dbcp2:
      min-idle: 8
      initial-size: 10
      max-total: 7
      max-wait-millis: 600

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: 192.168.1.150:9092
#    bootstrap-servers: 101.133.167.25:9092,101.133.172.253:9092,101.132.105.199:9092
#    bootstrap-servers: datanode1:9092,datanode2:9092,datanode3:9092
    producer:
      acks : 1
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: guoch008
      auto-offset-reset: earliest
#      auto-offset-reset: latest
      auto-commit-interval: 100
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  listener:
    concurrencys: 3,6
datetime:
  kafka2mysql:
    start-landing-time: 2020-04-16 15:00:00